### ISSUE TITLE
Phantom Left

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [ekmett/profunctors#113]
It would be useful to have a type like (hate the name)

```haskell
newtype PhantomLeft m a b = PhantomLeft (m b)
```

so that `Profunctor` could be derived for types with phantom variables.

**Comment by RyanGlScott** [comment]
I think you want [`Joker`](https://hackage.haskell.org/package/bifunctors-5.6.2/docs/Data-Bifunctor-Joker.html), which has instances for `Profunctor` and friends defined in this library.

**Comment by BebeSparkelSparkel** [comment]
Thanks, I did not think to look in bifunctors for profunctor types.
