### ISSUE TITLE
Even more instances for DownStar?

### ISSUE THREAD

**Issue by Apsod** [ekmett/profunctors#21]
It seems like 
distribute ds = DownStar (\ga -> flip runDownStar ga <$> ds) 
is valid. 
But i had a hard time understanding which laws distributive instances must follow.

**Comment by ekmett** [comment]
That would appear to be a missing instance, yeah.

Basically every distributive instance `f` is isomorphic to a function (x ->)  for some representation `x` that we can't talk about without moving out of Haskell 98 to something like  `adjunctions`.

**Comment by ekmett** [comment]
There is a similar instance for UpStar.

**Comment by ekmett** [comment]
They are now in HEAD and should be in `profunctors` 5 when we ship it.

If you need these sooner I can backport them to `profunctors` 4.

**Comment by Apsod** [comment]
I'm not in desperate need of these. But thanks!
