### ISSUE TITLE
Why does Cosieve introduce a functional dependency from the Profunctor to the Functor

### ISSUE THREAD

**Issue by srijs** [ekmett/profunctors#31]
Stumbled upon this, and not understanding the theory behind it 100%, I am a bit puzzled.

Why can't a profunctor be a cosieve on multiple functors?

**Comment by ekmett** [comment]
It could, just like it could be representable by multiple (in that case, isomorphic) functors. 

Inference would be awful rendering the split of representable into sieve and representable less useful in practice than the original. 

With this inference is never worse.
