### ISSUE TITLE
Explain laws for Cochoice?

### ISSUE THREAD

**Issue by Zemyla** [ekmett/profunctors#36]
Does Cochoice have laws? Am I right in assuming that its gist is basically "If you get a value on the wrong side, pass it back in again until you get one on the correct side"? If so, then wouldn't any ArrowChoice also be a Cochoice, with:

``` haskell
unright :: (ArrowChoice p) => p (Either a c) (Either b c) -> p a b
unright a = let go = ((go . arr Left) ||| id) . a in go . arr Right
```

That seems to be equivalent to the instance definition for Cochoice (->).

**Comment by phadej** [comment]
Isn't this done as part of solving #38?

![image](https://cloud.githubusercontent.com/assets/51087/24586688/52ab0f7a-17af-11e7-9d27-cb8f94995920.png)

**Comment by ekmett** [comment]
Fixed.
