### ISSUE TITLE
Laws for strong profunctors?

### ISSUE THREAD

**Issue by mpickering** [ekmett/profunctors#38]
It seems like there should be some laws for strong profunctors. I couldn't find anything written down anywhere.

Maybe something like

```
first' . dimap f g = dimap (first f) (first g) . first'
```

but are there any other equations which are expected to hold?

**Comment by ekmett** [comment]
Section 7 of https://arxiv.org/pdf/1406.4823.pdf gives the laws for a strong profunctor. We should probably transcribe them into the haddocks in a haskell-readable form.

**Comment by ekmett** [comment]
This, and the extended mission of stating all the laws, should now be handled in HEAD
