### ISSUE TITLE
Traversing1 class

### ISSUE THREAD

**Issue by phadej** [ekmett/profunctors#46]
I'd like to have that for completeness, but it would depend on having `Traversable1`.

It have to be in the same package where `Traversing` is defined, as `(Traversing1 p, Choice p) => Traversing p`.

**Comment by ekmett** [comment]
It'd have to live in `semigroupoids`, which acts as the sort of sin-bin for all the `Traversable1`, `Apply`, etc. garbage. `profunctors` is intended to live lower on the dependency tree.

**Comment by ekmett** [comment]
Feel free to open an issue of fix this there.
