### ISSUE TITLE
Why there is `Star`

### ISSUE THREAD

**Issue by phadej** [ekmett/profunctors#51]
Does it has different instances than `Kleisli`?

We should clarify that in haddocks.

*EDIT* is that `Star` uses `Applicative`, and `Kleisli` uses `Monad`?

**Comment by arianvp** [comment]
`Star` is _exactly_ Kleisli afaik


However, it is missing:

```
(Monad f) => Category (Star f)
```

Though that can be trivially defined using `>=>`

Why is that instance not there?

In purescript, `Kleisli` does not exist. Only `Star`:
https://pursuit.purescript.org/packages/purescript-profunctor/3.0.0/docs/Data.Profunctor.Star#t:Star

**Comment by arianvp** [comment]
They also seem to have very similar `Strong` instances... https://www.stackage.org/haddock/lts-8.13/profunctors-5.2/src/Data.Profunctor.Strong.html#line-97

**Comment by ekmett** [comment]
Because compilers from before the applicative monad proposal exist.

That and Kleisli signals a very specific intent in categroy theory.

**Comment by ekmett** [comment]
There is no moral objection on my part to adding the Categroy instance

**Comment by arianvp** [comment]
@phadej would this be satisfactory to you?  This would close the gap, making them morally equivalent as far as I know.

**Comment by arianvp** [comment]
Can we close this issue and tag a new release?

**Comment by RyanGlScott** [comment]
I've uploaded [`profunctors-5.2.1`](http://hackage.haskell.org/package/profunctors-5.2.1) to Hackage with this change.
