### ISSUE TITLE
Product profunctors

### ISSUE THREAD

**Issue by mitchellwrosen** [ekmett/profunctors#57]
Just curious, are there any plans to eventually merge https://hackage.haskell.org/package/product-profunctors into this package?

**Comment by sboosali** [comment]
fwiw

> I don't actually use [ProductProfunctors] myself, hence why it is packaged up by tomjaguarpaw and not me.

https://www.reddit.com/r/haskell/comments/5wf49a/didnt_struggle_with_monads_as_much_as_were/deauzyz/

**Comment by ekmett** [comment]
HEAD has a notion of monoidal profunctor and day convolution included. Not sure how closely it follows `product-profunctors`. I should eyeball if the API can be kept roughly consistent with it at some point.
