### ISSUE TITLE
Functor superclass

### ISSUE THREAD

**Issue by andrewthad** [ekmett/profunctors#74]
With `QuantifiedConstraints`, it becomes possible to add a `Functor` superclass constraint:

    instance (forall a. Functor (f a)) => Profunctor f

I don't know if this is a direction `profunctors` ever wants to go. This originally came up on a [trac ticket about about moving `Profunctor` into `base`](https://gitlab.haskell.org/ghc/ghc/issues/16173).

**Comment by andrewthad** [comment]
There is already a PR for this at https://github.com/ekmett/profunctors/pull/70

**Comment by ekmett** [comment]
Implemented in HEAD
