### ISSUE TITLE
More methods

### ISSUE THREAD

**Issue by treeowl** [ekmett/profunctors#77]
Since we have `wander` and `roam`, I believe we should also have, in `Strong`, a method (whose name and default implementation I've borrowed from `mezzolens`)

```haskell
lensVL :: (forall f. Functor f => (a -> f b) -> s -> f t) -> p a b -> p s t
lensVL l = dimap (unPStore #. l (\q -> PStore (id, q))) (uncurry id) . second'

newtype PStore i j x = PStore {unPStore :: (j -> x, i)}
  deriving Functor
```

This is, of course, sufficient to define `first'` and `second'`:

```haskell
-- | A definition of 'first'' for a 'Strong' instance defining 'lensVL'
firstVL :: Strong p => p a b -> p (a, c) (b, c)
firstVL = lensVL $ \afb ~(a, c) -> (\b -> (b, c)) <$> afb a

-- | A definition of 'second'' for a 'Strong' instance defining 'lensVL'
secondVL :: Strong p => p a b -> p (c, a) (c, b)
secondVL = lensVL $ \afb ~(c, a) -> (\b -> (c, b)) <$> afb a
```

Playing around in this space, I believe I've found two additional methods, each of which would be sufficient on its own:

```haskell
first'' :: p a b -> p a (a, b)
second'' :: p a b -> p a (b, a)
```

These are rather minimalist, but it's pretty cool to see they do the trick. Similarly, for `Costrong`, I believe these are each sufficient:

```haskell
unfirst' :: p (a, b) b -> p a b
unsecond' :: p (b, a) b -> p a b
```

I doubt any of these four latter "methods" should actually be a method, but maybe they serve some documentary value.

**Comment by Zemyla** [comment]
You don't need to have the new `PStore` functor. `Compose ((,) a) ((->) b)` works perfectly well:

```haskell
lensVL :: (forall f. Functor f => (a -> f b) -> s -> f t) -> p a b -> p s t
lensVL l = dimap (getCompose #. l (\a -> Compose (a, id))) (uncurry (flip id)) . first'
```

**Comment by ekmett** [comment]
Implemented (as a top level definition) in HEAD
