### ISSUE TITLE
Chocolate Profunctor - Co(ntravariant) Closed

### ISSUE THREAD

**Issue by lemastero** [ekmett/profunctors#87]
@Icelandjack tweet https://twitter.com/Iceland_jack/status/1238581538557767680 got me thinking. Those isomorphisms:
```
(->A) ~> (->B)   ~   A->B
(A->) ~> (B->)   ~   B->A
```
we could write down as:
```
(->A) ~> (->B)   ~   A->B
(B->) ~> (A->)   ~   A->B
```

`(->A) ~> (->B)   ~   A->B`  is generalized to arbitrary profunctor by [Closed](http://hackage.haskell.org/package/profunctors/docs/Data-Profunctor-Closed.html).
```Haskell
class Profunctor p => Closed p where
  closed :: p a b -> p (x -> a) (x -> b)
```

`(B->) ~> (A->)   ~   A->B` could be generalized in similar way:

```Haskell
class Profunctor p => Chocolate p where
  mirala :: p a b -> p (b -> x) (a -> x)
```
we can define instance for ->
```Haskell
instance Chocolate (->) where
  mirala f g = flip (.)
```

1) WDYT about this?
2) Is there something similar in category theory? I do no see correspondence to [co-CCC](https://ncatlab.org/nlab/show/cocartesian+closed+category), but maybe my CT-fu is not strong enough.

**Comment by ekmett** [comment]
I'm having trouble coming up with non-trivial instances beyond products and sums of `(->)` with `(->)`
