### ISSUE TITLE
Compatibility with transformers 0.6

### ISSUE THREAD

**Issue by sjakobi** [ekmett/profunctors#98]
https://hackage.haskell.org/package/transformers-0.6.0.0/changelog

Could you upload a compatible release or make a Hackage revision?

**Comment by RyanGlScott** [comment]
The following dependencies, which also impose an upper version bound of `transformers < 0.6`, will need to be addressed first:

* [ ] `StateVar`
* [ ] `bifunctors`
* [ ] `comonad`
* [ ] `contravariant`
* [ ] `indexed-traversable`
* [ ] `tagged`

**Comment by sjakobi** [comment]
I have opened https://github.com/haskell-opengl/StateVar/issues/10.

**Comment by phadej** [comment]
`transformers-compat` should be first on the list.

**Comment by sjakobi** [comment]
> `transformers-compat` should be first on the list.

See https://github.com/ekmett/transformers-compat/issues/48.

**Comment by RyanGlScott** [comment]
I had a feeling that I had forgotten a dependency. I've added `transformers-compat` to the list in https://github.com/ekmett/profunctors/issues/98#issuecomment-882565028.

**Comment by phadej** [comment]
`mtl`:

```
[ 1 of 22] Compiling Control.Monad.Cont.Class ( Control/Monad/Cont/Class.hs, dist/build/Control/Monad/Cont/Class.o )

Control/Monad/Cont/Class.hs:58:1: error:
    Could not load module ‘Control.Monad.Trans.Error’
    It is a member of the hidden package ‘transformers-0.5.6.2’.
```

**Comment by phadej** [comment]
`contravariant`

```
Building library for contravariant-1.5.4..

old-src/Data/Functor/Contravariant.hs:69:8:
    Could not find module ‘Control.Monad.Trans.Error’
```

**Comment by phadej** [comment]
```
allow-newer: bifunctors:transformers
allow-newer: bifunctors:transformers-compat
allow-newer: comonad:transformers
allow-newer: distributive:transformers
```

Seems to be safe to relax

**Comment by RyanGlScott** [comment]
I've pushed commits which raise the upper version bounds on `transformers`:

* 7070eae to the `main` branch, and
* 04ccce2 to the `5` branch.

I've also made a corresponding Hackage revision to `profunctors-5.6.2` [here](https://hackage.haskell.org/package/profunctors-5.6.2/revisions/). I believe that takes care of everything, but do re-open this issue if I've forgotten something.
